routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/' ,'FrontEndController@index');



Route::resource('Product','ProductController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/singleproduct/{id}','FrontEndController@show')->name('single');

Route::post('/shop','ShoppingController@add')->name('addtoshoppingcart');
Route::get('/shop','ShoppingController@viewcart')->name('viewcart');

Route::get('/remove/{id}','ShoppingController@deleteitem');

Route::get('/cart/rem/{id}/{qty}','ShoppingController@removeoneitem');

Route::get('/cart/addy/{id}/{qty}','ShoppingController@addoneitem');

Route::get('/quickproduct/{id}','ShoppingController@quickadd');

Route::get('checkout','CheckoutController@checkout');

Route::post('/pay','CheckoutController@pay')->name('pay');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CheckoutController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Cart;
use Mail;
use App\Mail\successfulpurchase;


class CheckoutController extends Controller
{
    public function checkout(){



    	return view('checkout');
    }

    public function pay(){


    	// Set your secret key: remember to change this to your live secret key in production
// See your keys here: https://dashboard.stripe.com/account/apikeys
\Stripe\Stripe::setApiKey("sk_test_4IOKcwUL2UorU0BbnhE46nuN");

// Token is created using Checkout or Elements!
// Get the payment token ID submitted by the form:
$token = $_POST['stripeToken'];

// Charge the user's card:
$charge = \Stripe\Charge::create(array(
  "amount" =>Cart::total()*100,
  "currency" => "usd",
  "description" => "the book store",
  "source" => $token,
));

Mail::to(request()->stripeEmail)->send(new successfulpurchase());

Cart::destroy();

return redirect('/');

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FrontEndController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class FrontEndController extends Controller
{
    public function index(){

    	$allproducts = Product::paginate(6);

    	

    	return view('index')->with('allproducts',$allproducts);


    }

    public function show($id){

    	$theproduct = Product::find($id);

    	return view('singleproduct')->with('theproduct',$theproduct);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $allProducts = Product::paginate(10);
        return view('products.index')->with('allProducts',$allProducts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

                'name'=>'required',
                'description'=>'required',
                'price'=>'required|numeric',
                'image'=>'required|image',


        ]);

        $newproduct = new Product;

        $newproduct->name = $request->name;
        $newproduct->description =  $request->description;
        $newproduct->price = $request->price;

        $productimage = $request->image;

        $newimagename = time().$productimage->getClientOriginalName();

        $productimage->move('uploads/products',$newimagename);

        $newproduct->image ='uploads/products/'.$newimagename;

        $newproduct->save();

        return redirect()->route('Product.index');

        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $theproduct = Product::find($id);

        
        return view('Products.edit')->with('theproduct',$theproduct);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);

        $product->name = $request->name;
        $product->description = $request->description;
        $product->price = $request->price;

        if($request->hasFile('image')){

            $productimage = $request->image;
            $newimagename = time().$productimage->getClientOriginalName();

            $productimage->move('uploads/products',$newimagename);
            $product->image = 'uploads/products'.$newimagename;
        }

        $product->save();

        return redirect()->Route('Product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);

        if(file_exists($product->image)){

            unlink($product->image);
        }

        $product->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/ShoppingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Cart;
use App\Product;

class ShoppingController extends Controller
{
    

    public function add(){



    	$product = Product::find(request()->id);

    	

    	$thecart = Cart::add($product->id,$product->name,request()->quantity,$product->price);

    	$thecart->associate('App\Product');



    	return view('cart');


    }

    public function deleteitem($id){


    	Cart::remove($id);

    	return view('cart');
    }

    public function removeoneitem($id,$qty){


    	Cart::update($id,$qty-1);

    	return view('cart');
    }

        public function addoneitem($id,$qty){


    	Cart::update($id,$qty+1);

    	return view('cart');
    }

    public function viewcart(){


    	return view('cart');
    }

    public function quickadd($id){


    	$product = Product::find($id);

    	

    	$thecart = Cart::add($product->id,$product->name,1,$product->price);

    	$thecart->associate('App\Product');



    	return redirect()->back();
    }


}

resources/views/Products/create.blade.php
@extends('layouts.app')



@section('content')


<div class="container">
	
   @if($errors->any())

     {{$errors}}

   @endif
	<div class="row">
		
		<form action="/Product" method="post" enctype="multipart/form-data">

			@csrf

			<div class="form-group">
				
				<label for="image">Book name</label>
				<input type="text" name="name" class="form-control">
			</div>

			<div class="form-group">
    <label for="exampleFormControlTextarea1">Example textarea</label>
    <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3" cols='100'></textarea>
  </div>
			<div class="form-group">
                              <label for="image">Price</label>
                              <input type="number" name="price" class="form-control" value="{{ old('price') }}">
</div>
			

						<div class="form-group">
                              <label for="image">Price</label>
                              <input type="file" name="image" class="form-control">
</div>
 <div class="form-group">	<button class="form-control btn btn-success">Save Product</button></div>






		</form>

	</div>
</div>

@endsection

resources/views/Products/edit.blade.php
@extends('layouts.app')



@section('content')


<div class="container">
	
   @if($errors->any())

     {{$errors}}

   @endif
	<div class="row">
		
		<form action="/Product/{{$theproduct->id}}" method="post" enctype="multipart/form-data">

			@method('put')

			@csrf

			<div class="form-group">
				
				<label for="image">Book name</label>
				<input type="text" name="name" class="form-control" value="{{$theproduct->name}}">
			</div>

			<div class="form-group">
    <label for="exampleFormControlTextarea1">Description of the Product</label>
    <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3" cols='100'>{{$theproduct->description}}</textarea>
  </div>
			<div class="form-group">
                              <label for="image">Price</label>
                              <input type="number" name="price" class="form-control" value="{{$theproduct->price}}">
</div>
			

						<div class="form-group">
                              <label for="image">Image</label>
                              <input type="file" name="image" class="form-control">
</div>
 <div class="form-group">	<button class="form-control btn btn-success">Update Product</button></div>






		</form>

	</div>
</div>

@endsection

resources/views/Products/index.blade.php
@extends('layouts.app')


@section('content')

<div class="container">


	<div class="row">
		

       <table class="table table-striped">
  <thead>
    <tr>
      
      <th scope="col">name</th>
      <th scope="col">Price</th>
      <th scope="col">image</th>
      <th scope="col">edit</th>
      <th scope="col">delete</th>
    </tr>
  </thead>
  <tbody>
  	@foreach($allProducts as $product)
    <tr>
      
      <td>{{$product->name}}</td>
      <td>{{$product->price}}</td>
      <td><img src="{{asset($product->image)}}" height=40 width=30></td>
      <td><a href="/Product/{{$product->id}}/edit" class="btn btn-sm btn-info">Edit</a></td>
      <td><form action="/Product/{{$product->id}}" method="post">@method('DELETE') @csrf<button class="btn btn-danger btn-sm" type="submit">Delete</button>  </form>  </td>
    </tr>
    @endforeach
  </tbody>
</table>

	{{$allProducts->links()}}


	</div>
	






</div>


@endsection

resources/views/cart.blade.php
@extends('layouts.frontend')



@section('page')






<!-- Books products grid -->

<div class="container-fluid">
    <div class="row bg-border-color medium-padding120">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">

                    <div class="cart">

                        <h1 class="cart-title">In Your Shopping Cart: <span class="c-primary"> {{Cart::count()}} items</span></h1>

                    </div>

                    <form action="#" method="post" class="cart-main">

                        <table class="shop_table cart">
                            <thead class="cart-product-wrap-title-main">
                            <tr>
                                <th class="product-remove">&nbsp;</th>
                                <th class="product-thumbnail">Product</th>
                                <th class="product-price">Price</th>
                                <th class="product-quantity">Quantity</th>
                                <th class="product-subtotal">Total</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach(Cart::content() as $oneitem)
                            <tr class="cart_item">

                                <td class="product-remove">
                                    <a href="/remove/{{$oneitem->rowId}}" class="product-del remove" title="Remove this item">
                                        <i class="seoicon-delete-bold"></i>
                                    </a>
                                </td>

                                <td class="product-thumbnail">

                                    <div class="cart-product__item">
                                        <a href="#">
                                            <img src="{{asset($oneitem->model->image)}}" alt="product" class="attachment-shop_thumbnail size-shop_thumbnail wp-post-image">
                                        </a>
                                        <div class="cart-product-content">
                                            
                                            <h5 class="cart-product-title">{{$oneitem->name}}</h5>
                                        </div>
                                    </div>
                                </td>

                                <td class="product-price">
                                    <h5 class="price amount">${{$oneitem->price}}</h5>
                                </td>

                                <td class="product-quantity">

                                    <div class="quantity">
                                        <a href="/cart/rem/{{$oneitem->rowId}}/{{$oneitem->qty}}" class="quantity-minus-d">-</a>
                                        <input title="Qty" class="email input-text qty text" type="text"  value="{{$oneitem->qty}}" >
                                        <a href="/cart/addy/{{$oneitem->rowId}}/{{$oneitem->qty}}" class="quantity-plus-d">+</a>
                                    </div>

                                </td>

                                <td class="product-subtotal">
                                    <h5 class="total amount">${{$oneitem->price * $oneitem->qty }}</h5>
                                </td>

                            </tr>

                            @endforeach

                            

                            <tr>
                                <td colspan="5" class="actions">

                                    <div class="coupon">
                                        <input name="coupon_code" class="email input-standard-grey" value="" placeholder="Coupon code" type="text">
                                        <div class="btn btn-medium btn--breez btn-hover-shadow">
                                            <span class="text">Apply Coupon</span>
                                            <span class="semicircle--right"></span>
                                        </div>
                                    </div>

                                    <div class="btn btn-medium btn--dark btn-hover-shadow">
                                        <span class="text">Apply Coupon</span>
                                        <span class="semicircle"></span>
                                    </div>

                                </td>
                            </tr>

                            </tbody>
                        </table>


                    </form>

                    <div class="cart-total">
                        <h3 class="cart-total-title">Cart Totals</h3>
                        <h5 class="cart-total-total">Total: <span class="price">${{Cart::total()}}</span></h5>
                        <a href="/checkout" class="btn btn-medium btn--light-green btn-hover-shadow">
                            <span class="text">Checkout</span>
                            <span class="semicircle"></span>
                        </a>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

<!-- End Books products grid -->



@endsection

resources/views/checkout.blade.php
@extends('layouts.frontend')



@section('page')
<div class="container-fluid">
	<div class="row medium-padding120 bg-border-color">
		<div class="container">

			<div class="row">

				<div class="col-lg-12">
			<div class="order">
				<h2 class="h1 order-title text-center">Your Order</h2>
				<form action="{{route('pay')}}" method="post" class="cart-main">
					<table class="shop_table cart">
						<thead class="cart-product-wrap-title-main">
						<tr>
							<th class="product-thumbnail">Product</th>
							<th class="product-quantity">Quantity</th>
							<th class="product-subtotal">Total</th>
						</tr>
						</thead>
						<tbody>

						@foreach(Cart::content() as $product)

						<tr class="cart_item">

							<td class="product-thumbnail">

								<div class="cart-product__item">
									<div class="cart-product-content">
										<h5 class="cart-product-title">{{$product->name}}</h5>
									</div>
								</div>
							</td>

							<td class="product-quantity">

								<div class="quantity">
									x {{$product->qty}}
								</div>

							</td>

							<td class="product-subtotal">
								<h5 class="total amount">${{$product->price * $product->qty }}</h5>
							</td>

						</tr>
						@endforeach



						<tr class="cart_item subtotal">

							<td class="product-thumbnail">


								<div class="cart-product-content">
									<h5 class="cart-product-title">	Subtotal:</h5>
								</div>


							</td>

							<td class="product-quantity">

							</td>

							<td class="product-subtotal">
								<h5 class="total amount">${{Cart::subtotal()}}</h5>
							</td>
						</tr>

						<tr class="cart_item total">

							<td class="product-thumbnail">


								<div class="cart-product-content">
									<h5 class="cart-product-title">Total:</h5>
								</div>


							</td>

							<td class="product-quantity">

							</td>

							<td class="product-subtotal">
								<h5 class="total amount">${{Cart::total()}}</h5>
							</td>
						</tr>

						</tbody>
					</table>

					<div class="cheque">

						<div class="logos">
							<a href="#" class="logos-item">
								<img src="{{asset('app/img/visa.png')}}" alt="Visa">
							</a>
							<a href="#" class="logos-item">
								<img src="{{asset('app/img/mastercard.png')}}" alt="MasterCard">
							</a>
							<a href="#" class="logos-item">
								<img src="{{asset('app/img/discover.png')}}" alt="DISCOVER">
							</a>
							<a href="#" class="logos-item">
								<img src="{{asset('app/img/amex.png')}}" alt="Amex">
							</a>
							
							<span style="float: right;">
								
									@csrf
											  <script
											    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
											    data-key="pk_test_1X9rXxiZZvg4B7bDp3Cc2ZYN"
											    data-amount="{{Cart::total() *100}}"
											    data-name="Bookstore"
											    data-description="we like books"
											    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
											    data-locale="auto">
											  </script>
								
							</span>
						</div>
					</div>

				</form>
			</div>
		</div>

			</div>
		</div>
	</div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/includes/footerfrontend.blade.php
<!-- Footer -->

<footer class="footer">
    <div class="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                </div>
            </div>
        </div>
    </div>
</footer>



<script src="{{ asset('app/js/jquery-2.1.4.min.js')}}"></script>
<script src="{{ asset('app/js/crum-mega-menu.js')}}"></script>
<script src="{{asset('app/js/swiper.jquery.min.js')}}"></script>
<script src="{{asset('app/js/theme-plugins.js')}}"></script>
<script src="{{asset('app/js/main.js')}}"></script>
<script src="{{asset('app/js/form-actions.js')}}"></script>

<script src="{{asset('app/js/velocity.min.js')}}"></script>
<script src="{{asset('app/js/ScrollMagic.min.js')}}"></script>
<script src="{{asset('app/js/animation.velocity.min.js')}}"></script>

<!-- ...end JS Script -->

resources/views/includes/headerfrontend.blade.php
<body class=" ">
<header class="header" id="site-header">

    <div class="container">

        <div class="header-content-wrapper">

            <ul class="nav-add">
                <li class="cart">

                    <a href="#" class="js-cart-animate">
                        <i class="seoicon-basket"></i>
                        <span class="cart-count">{{Cart::count()}}</span>
                    </a>

                    <a href="/shop"><div class="cart-popup-wrap">
                        <div class="popup-cart">
                            <h4 class="title-cart">{{Cart::count()}} products in the cart!</h4>
                            <p class="subtitle">${{Cart::total()}}</p>
                            <div class="btn btn-small btn--dark">
                                <span class="text">view cart</span>
                            </div>
                        </div>
                    </div></a>

                </li>
            </ul>
        </div>

    </div>

</header>

resources/views/includes/headfrontend.blade.php
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Seosight - Shop</title>

    <link rel="stylesheet" type="text/css" href="{{asset('app/css/fonts.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('app/css/crumina-fonts.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('app/css/normalize.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('app/css/grid.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('app/css/styles.css')}}">


    <!--Plugins styles-->

    <link rel="stylesheet" type="text/css" href="{{asset('app/css/jquery.mCustomScrollbar.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('app/css/swiper.min.cs')}}s">
    <link rel="stylesheet" type="text/css" href="{{asset('app/css/primary-menu.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('app/css/magnific-popup.css')}}">

    <!--Styles for RTL-->

    <!--<link rel="stylesheet" type="text/css" href="css/rtl.css">-->

    <!--External fonts-->

    <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>

</head>

resources/views/includes/slogan.blade.php
<div class="container">
        <div class="row pt120">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="heading align-center mb60">
                    <a href="/"><h4 class="h1 heading-title">Udemy E-commerce tutorial</h4></a>
                    <p class="heading-text">Buy books, and we ship to you.
                    </p>
                </div>
            </div>
        </div>
    </div>

resources/views/index.blade.php
@extends('layouts.frontend')


@section('page')


    <div class="container">
        <div class="row pt120">

            <div class="books-grid">

            <div class="row mb30">
                 @foreach($allproducts as $book)
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                   
                    <div class="books-item">
                        <div class="books-item-thumb">
                            <img  src="{{asset($book->image)}}" alt="book">
                            <div class="new">New</div>
                            <div class="sale">Sale</div>
                            <a href="/singleproduct/{{$book->id}}"><div class="overlay overlay-books"></div></a>
                        </div>

                        <div class="books-item-info">
                           <a href="/singleproduct/{{$book->id}}"><h5 class="books-title">{{$book->name}}</h5></a> 

                            <div class="books-price">{{$book->price}}</div>
                        </div>

                        <a href="/quickproduct/{{$book->id}}" class="btn btn-small btn--dark add">
                            <span class="text">Add to Cart</span>
                            <i class="seoicon-commerce"></i>
                        </a>

                    </div>
                    
                </div>
                @endforeach
            </div>

           

            <div class="row pb120">

                <div class="col-lg-12">

                    <!-- <nav class="navigation align-center">
                    
                        <a href="#" class="page-numbers bg-border-color current"><span>1</span></a>
                        <a href="#" class="page-numbers bg-border-color"><span>2</span></a>
                        <a href="#" class="page-numbers bg-border-color"><span>3</span></a>
                        <a href="#" class="page-numbers bg-border-color"><span>4</span></a>
                        <a href="#" class="page-numbers bg-border-color"><span>5</span></a>
                    
                        <svg class="btn-prev">
                            <use xlink:href="#arrow-left"></use>
                        </svg>
                        <svg class="btn-next">
                            <use xlink:href="#arrow-right"></use>
                        </svg>
                    
                    </nav>
                     -->

                      {{$allproducts->links()}}
                </div>

            </div>
        </div>
        </div>
    </div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                       <li><a href="{{route('Product.index')}}">Products</a> </li> 
                       <li style="margin-left:8px;"><a href="{{route('Product.create')}}">Create Product</a></li> 

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/frontend.blade.php
<!DOCTYPE html>
<html lang="en">

@include('includes.headfrontend')




@include('includes.headerfrontend')


<div class="content-wrapper">

@include('includes.slogan')

    <!-- End Books products grid -->

@yield('page')
</div>

@include('includes.footerfrontend')


</body>

<!-- Mirrored from theme.crumina.net/html-seosight/16_shop.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 27 Nov 2016 13:03:04 GMT -->
</html>